language: java
git:
  depth: false
cache:
  directories:
  - "$HOME/.m2"
addons:
  sonarcloud:
    organization: sudiamanj-github
    token:
      secure: r85VgPtPQetKisEGg8t1mMf9TQNc0xrN6U77PE/DswlvogD/kVzOYZDGAz2XUFYbe/pofHAOXYTP8LfnfudfYlAgPlT3QkMvMJAjS5G1X6exnELsOEU30nh2oN/bFEDvkYDEIxB83bjeo3G6zmbC8vzCqyQYc8cDPZkdJOvIbh/ATYOYBJOngQzhsXnp9PMDOLuEykzVo3P34OF6Oe7mtBwuTqp4np8Wl5yuQmFcp4wPcx6iTvRMCy2TIpnvaKIiLfrgbFM7DtocE6ZdAKP7hphtN5it7TZaWbupx55iiqD6PeLpa9t9rZ7hSypfuXsgAnFO3fC+YtmjbgZFygsE6im1XocVJK5pX/pMUi/n33HF39k5vDw1PZ6CP8WWOe+ecLem7tffZX53gIX/0iaAzXIxkAkPhLZ8uAWHYycPYxN/xZWzutstctvHs9VNSfMBwnifzdkr+fWEtxx6LzRsVEMlFWgjZIJrY64g2j51NLqaFY8EBp4O3aufrjf55ioawNYhtHmTZxDcw0NoW6Ob6uRMnKYyTgscmMF4g5KojVhhlCk30ir8aK1eCtWte8m1iT8jsFP8dyWejOwW7sOKkyxqgfgHE1B2za6BMFYDI3ugvKzy70GpH06buaaY8JNVIX5CC9QpPSwJS5Ma8QogLwAnjbBSv9Bdm3zUNaFlnQ4=
script:
- mvn clean install sonar:sonar -Dsonar.projectKey=sudiamanj_fogbugz-to-github
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: ./target/apidocs
  fqdn: fb2gh.sudicode.com
  on:
    branch: master
env:
  global:
    secure: bgYOzaqFuiGxf9juwRcK6AeAhWFDwD1MQzxR6dJlkDwh7xE2iEEK4kEdwi7+EfwqwqKFpODawYpmPnHQbbc1+/5m+HUDkjNPqP5Oq8s6vfmZ9NDfWztHoDZ+8OJMJNu4/mBPyI1VCxRnnpU+GnrRrNi78GWgPG9E3aPSv1t1qv37jqbA6ZcWQThoDU5wA344CqBsCmDZbHubNa7HlV1rudGnajyZLrswVcSTTt6BKKPoqOB7BGZvYLruWWKgyr5zq8MV7RQErCVpGEBX/LUXBzy1A3KAN1ujXZ6GuWoh7Umy5rB28hIQEt853o6cDLazeETWI/OMUD9MlN/rWVEcFavcux/OmgC/KEK6+mCTXWl2LpZgIDw1CjzMBhUQFu38/rLAdn3kFDH9vIlB4BuH5yfwt4fFmIt59ADNzyStxVBOx3BcJYR5rbbSQxKBhiozsqVLrpWqJNs/TarLj0t361io8WuIXk0AfuTaz0MW53dPmgKqOMaA10Kkrs7ReGecPKrN8gmt6Oj5CoY69pyhAEXCRbQ7VHOzTP66beh/L46bIOqKQzu+3tevfknqgzTbbqK4o9h9msViVjGiLO4Jr0aJyse5A8X9Az5SvOWKM4rQzSgtmwgkQfKw5+eNEOGDeDafzEyOrVo/IQeKKO3fGYohglTUVAZGIwhDc4GEmms=
